### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by thenetexperts** [TheCadien/SuluImportExportBundle#1]
Few points for the basic readme:

- When using composer, currently no tag can be found. A quick-fix is using dev-master, though is not the recommended way.
- If using jackrabbit as phpcr adapter you also need to backup jackrabbit. This bundle is handling that.
- After database import you need to reindex using bin/adminconsole massive:search:reindex and bin/websiteconsole massive:search:reindex.  (Not sure if your bundle handles that aswell, i guess it does)

**Comment by TheCadien** [comment]
Thank you @thenetexperts , i released the first version of the Bundle. So the first point should work now. 
I think the secound and last point are't needed in a readme.
